name: Convox Export
description: Export a resource to a file
author: Convox
branding:
  icon: download
  color: blue
inputs:
  rack:
    description: Convox Rack name
    required: true
  app:
    description: Convox app name
    required: true
  resource:
    description: The resource to run the export command against
    required: true
  filename:
    description: The name of the output file
    required: true

runs:
  using: docker
  image: Dockerfile